version: "2"

services:
  discovery:
    # image: "msdaf/discovery-service" #test local build
    image: "msdaf/netflix-eureka" #production cloud build
    hostname: discovery
    ports:
      - "8761:8761"

  config:
    # image: "msdaf/config-server" #test local build
    image: "msdaf/config" #production cloud build
    hostname: config
    restart: always
    links:
      - discovery
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "8888:8888"

  gateway:
    image: "msdaf/netflix-zuul"
    hostname: gateway
    restart: always
    links:
      - discovery
      - config
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "8080:8080"

  anvisa:
    image: "msdaf/anvisa" #"msdaf/anvisa" #"anvisa"
    hostname: anvisa
    restart: always
    links:
      - discovery
      - config
      - gateway
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
    ports:
      - "8542:5000"

  ibge:
    image: "msdaf/ibge" #"msdaf/ibge" #"ibge"
    hostname: ibge
    restart: always
    links:
      - discovery
      - config
      - gateway
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
    ports:
      - "8531:5000"

  ui:
    image: "msdaf/ui" #msdaf/ui #ui:0.0.1
    hostname: ui
    restart: always
    links:
      - discovery
      - config
      - gateway
      - anvisa
      - ibge
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "8447:5000" #8443 reserved for SSL (HTTPS)
