version: "2"

services:
  discovery:
    # image: "msdaf/discovery-service" #test local build
    image: "msdaf/netflix-eureka" #production cloud build
    hostname: discovery
    ports:
      - "8761:8761"
    networks:
      - lognet

  config:
    # image: "msdaf/config-server" #test local build
    image: "msdaf/config" #production cloud build
    hostname: config
    restart: always
    links:
      - discovery
    depends_on:
      - discovery
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "8888:8888"
    networks:
      - lognet

  gateway:
    image: "msdaf/netflix-zuul"
    hostname: gateway
    restart: always
    links:
      - discovery
      - config
    depends_on:
      - discovery
      - config
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "8080:8080"
    networks:
      - lognet

  ui:
    # image: "msdaf/ui"
    hostname: ui
    restart: always
    build: .
    links:
      - discovery
      - config
      - gateway
    depends_on:
      - discovery
      - config
      - gateway
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    expose:
      - "80"
    ports:
      - "8447:80" #8443 reserved for SSL (HTTPS)
    networks:
      - lognet

networks:
  lognet:
    driver: bridge
