version: "2"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "daf2019"
    ports:
      - "5432:5432"
    volumes:
      - ../data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    restart: always

  mysqlsrv:
    image: mysql:5.7
    restart: always
    # volumes:
    #   - data:/var/lib/mysql
    #   - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"

  discovery:
    image: "gaesi/discovery" #production cloud build
    hostname: discovery
    ports:
      - "8761:8761"

  config:
    image: "gaesi/config" #production cloud build
    hostname: config
    restart: always
    links:
      - discovery
    environment:
       REPOSITORY_HOST: https://gitlab.com/gaesi/msdaf/config.git
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "8888:8888"

  gateway:
    image: "gaesi/gateway"
    hostname: gateway
    restart: always
    links:
      - discovery
      - config
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "8080:8080"

  # anvisa:
  #   image: "gaesi/anvisa" #"msdaf/anvisa" #"anvisa"
  #   hostname: anvisa
  #   restart: always
  #   links:
  #     - discovery
  #     - config
  #     - gateway
  #   environment:
  #     EUREKA_HOST: discovery
  #     EUREKA_PORT: 8761
  #   ports:
  #     - "8542:5000"
  #
  # ibge:
  #   image: "gaesi/ibge" #"msdaf/ibge" #"ibge"
  #   hostname: ibge
  #   restart: always
  #   links:
  #     - discovery
  #     - config
  #     - gateway
  #   environment:
  #     EUREKA_HOST: discovery
  #     EUREKA_PORT: 8761
  #   ports:
  #     - "8531:5000"

  parsers:
    image: "msdaf/parsers"
    hostname: parsers
    restart: always
    links:
      - mongodb
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
    ports:
      - "8445:5000"

  consultgru:
    image: "msdaf/consultgru"
    hostname: consultgru
    restart: always
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
    ports:
      - "8446:5000"

  budget:
    image: "msdaf/budget"
    hostname: budget
    restart: always
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
    ports:
      - "8447:5000"
    links:
      - postgres

  elucidation:
    image: "msdaf/elucidation"
    hostname: elucidation
    restart: always
    links:
      - mongodb
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
    ports:
      - "8448:5000"

  catmat:
    image: "msdaf/catmat"
    restart: always
    hostname: catmat
    links:
      - mysqlsrv
    depends_on:
      - mysqlsrv
      - discovery
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
      RAILS_ENV: development
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: pass
      DB_DATABASE: mydb
      DB_HOST: mysqlsrv
      SRV_PORT: 3000
    command: /bin/sh -c "rake db:create && rake db:recreate && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    ports:
      - "8450:3000"

  ui:
    image: "msdaf/ui"
    hostname: ui
    restart: always
    links:
      - discovery
      - config
      - gateway
      # - anvisa
      # - ibge
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "8450:5000" #8443 reserved for SSL (HTTPS)
